# Python stubs generated by omniidl from boggle.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "BoggleApp"
#
__name__ = "BoggleApp"
_0_BoggleApp = omniORB.openModule("BoggleApp", r"boggle.idl")
_0_BoggleApp__POA = omniORB.openModule("BoggleApp__POA", r"boggle.idl")


# struct Player
_0_BoggleApp.Player = omniORB.newEmptyClass()
class Player (omniORB.StructBase):
    _NP_RepositoryId = "IDL:BoggleApp/Player:1.0"

    def __init__(self, pid, username, points):
        self.pid = pid
        self.username = username
        self.points = points

_0_BoggleApp.Player = Player
_0_BoggleApp._d_Player  = (omniORB.tcInternal.tv_struct, Player, Player._NP_RepositoryId, "Player", "pid", omniORB.tcInternal.tv_long, "username", (omniORB.tcInternal.tv_string,0), "points", omniORB.tcInternal.tv_long)
_0_BoggleApp._tc_Player = omniORB.tcInternal.createTypeCode(_0_BoggleApp._d_Player)
omniORB.registerType(Player._NP_RepositoryId, _0_BoggleApp._d_Player, _0_BoggleApp._tc_Player)
del Player

# typedef ... PlayerList
class PlayerList:
    _NP_RepositoryId = "IDL:BoggleApp/PlayerList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_BoggleApp.PlayerList = PlayerList
_0_BoggleApp._d_PlayerList  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:BoggleApp/Player:1.0"], 0)
_0_BoggleApp._ad_PlayerList = (omniORB.tcInternal.tv_alias, PlayerList._NP_RepositoryId, "PlayerList", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:BoggleApp/Player:1.0"], 0))
_0_BoggleApp._tc_PlayerList = omniORB.tcInternal.createTypeCode(_0_BoggleApp._ad_PlayerList)
omniORB.registerType(PlayerList._NP_RepositoryId, _0_BoggleApp._ad_PlayerList, _0_BoggleApp._tc_PlayerList)
del PlayerList

# typedef ... WordList
class WordList:
    _NP_RepositoryId = "IDL:BoggleApp/WordList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_BoggleApp.WordList = WordList
_0_BoggleApp._d_WordList  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_BoggleApp._ad_WordList = (omniORB.tcInternal.tv_alias, WordList._NP_RepositoryId, "WordList", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_BoggleApp._tc_WordList = omniORB.tcInternal.createTypeCode(_0_BoggleApp._ad_WordList)
omniORB.registerType(WordList._NP_RepositoryId, _0_BoggleApp._ad_WordList, _0_BoggleApp._tc_WordList)
del WordList

# typedef ... LetterList
class LetterList:
    _NP_RepositoryId = "IDL:BoggleApp/LetterList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_BoggleApp.LetterList = LetterList
_0_BoggleApp._d_LetterList  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_char, 0)
_0_BoggleApp._ad_LetterList = (omniORB.tcInternal.tv_alias, LetterList._NP_RepositoryId, "LetterList", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_char, 0))
_0_BoggleApp._tc_LetterList = omniORB.tcInternal.createTypeCode(_0_BoggleApp._ad_LetterList)
omniORB.registerType(LetterList._NP_RepositoryId, _0_BoggleApp._ad_LetterList, _0_BoggleApp._tc_LetterList)
del LetterList

# exception NoUserFoundException
_0_BoggleApp.NoUserFoundException = omniORB.newEmptyClass()
class NoUserFoundException (CORBA.UserException):
    _NP_RepositoryId = "IDL:BoggleApp/NoUserFoundException:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_BoggleApp.NoUserFoundException = NoUserFoundException
_0_BoggleApp._d_NoUserFoundException  = (omniORB.tcInternal.tv_except, NoUserFoundException, NoUserFoundException._NP_RepositoryId, "NoUserFoundException", "message", (omniORB.tcInternal.tv_string,0))
_0_BoggleApp._tc_NoUserFoundException = omniORB.tcInternal.createTypeCode(_0_BoggleApp._d_NoUserFoundException)
omniORB.registerType(NoUserFoundException._NP_RepositoryId, _0_BoggleApp._d_NoUserFoundException, _0_BoggleApp._tc_NoUserFoundException)
del NoUserFoundException

# exception WordNotFoundException
_0_BoggleApp.WordNotFoundException = omniORB.newEmptyClass()
class WordNotFoundException (CORBA.UserException):
    _NP_RepositoryId = "IDL:BoggleApp/WordNotFoundException:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_BoggleApp.WordNotFoundException = WordNotFoundException
_0_BoggleApp._d_WordNotFoundException  = (omniORB.tcInternal.tv_except, WordNotFoundException, WordNotFoundException._NP_RepositoryId, "WordNotFoundException", "message", (omniORB.tcInternal.tv_string,0))
_0_BoggleApp._tc_WordNotFoundException = omniORB.tcInternal.createTypeCode(_0_BoggleApp._d_WordNotFoundException)
omniORB.registerType(WordNotFoundException._NP_RepositoryId, _0_BoggleApp._d_WordNotFoundException, _0_BoggleApp._tc_WordNotFoundException)
del WordNotFoundException

# interface PlayerServant
_0_BoggleApp._d_PlayerServant = (omniORB.tcInternal.tv_objref, "IDL:BoggleApp/PlayerServant:1.0", "PlayerServant")
omniORB.typeMapping["IDL:BoggleApp/PlayerServant:1.0"] = _0_BoggleApp._d_PlayerServant
_0_BoggleApp.PlayerServant = omniORB.newEmptyClass()
class PlayerServant :
    _NP_RepositoryId = _0_BoggleApp._d_PlayerServant[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_BoggleApp.PlayerServant = PlayerServant
_0_BoggleApp._tc_PlayerServant = omniORB.tcInternal.createTypeCode(_0_BoggleApp._d_PlayerServant)
omniORB.registerType(PlayerServant._NP_RepositoryId, _0_BoggleApp._d_PlayerServant, _0_BoggleApp._tc_PlayerServant)

# PlayerServant operations and attributes
PlayerServant._d_logInToGame = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_BoggleApp.NoUserFoundException._NP_RepositoryId: _0_BoggleApp._d_NoUserFoundException})
PlayerServant._d_getLeaderBoard = ((), (omniORB.typeMapping["IDL:BoggleApp/PlayerList:1.0"], ), None)
PlayerServant._d_getWaitingTime = ((), (omniORB.tcInternal.tv_long, ), None)
PlayerServant._d_startGame = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), None)
PlayerServant._d_getRoundTime = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), None)
PlayerServant._d_startRound = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_long, ), None)
PlayerServant._d_getLetterSet = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.typeMapping["IDL:BoggleApp/LetterList:1.0"], ), None)
PlayerServant._d_checkWord = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_boolean, ), {_0_BoggleApp.WordNotFoundException._NP_RepositoryId: _0_BoggleApp._d_WordNotFoundException})
PlayerServant._d_getRoundWinner = ((omniORB.tcInternal.tv_long, ), ((omniORB.tcInternal.tv_string,0), ), None)
PlayerServant._d_getGameWinner = ((omniORB.tcInternal.tv_long, ), ((omniORB.tcInternal.tv_string,0), ), None)

# PlayerServant object reference
class _objref_PlayerServant (CORBA.Object):
    _NP_RepositoryId = PlayerServant._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def logInToGame(self, *args):
        return self._obj.invoke("logInToGame", _0_BoggleApp.PlayerServant._d_logInToGame, args)

    def getLeaderBoard(self, *args):
        return self._obj.invoke("getLeaderBoard", _0_BoggleApp.PlayerServant._d_getLeaderBoard, args)

    def getWaitingTime(self, *args):
        return self._obj.invoke("getWaitingTime", _0_BoggleApp.PlayerServant._d_getWaitingTime, args)

    def startGame(self, *args):
        return self._obj.invoke("startGame", _0_BoggleApp.PlayerServant._d_startGame, args)

    def getRoundTime(self, *args):
        return self._obj.invoke("getRoundTime", _0_BoggleApp.PlayerServant._d_getRoundTime, args)

    def startRound(self, *args):
        return self._obj.invoke("startRound", _0_BoggleApp.PlayerServant._d_startRound, args)

    def getLetterSet(self, *args):
        return self._obj.invoke("getLetterSet", _0_BoggleApp.PlayerServant._d_getLetterSet, args)

    def checkWord(self, *args):
        return self._obj.invoke("checkWord", _0_BoggleApp.PlayerServant._d_checkWord, args)

    def getRoundWinner(self, *args):
        return self._obj.invoke("getRoundWinner", _0_BoggleApp.PlayerServant._d_getRoundWinner, args)

    def getGameWinner(self, *args):
        return self._obj.invoke("getGameWinner", _0_BoggleApp.PlayerServant._d_getGameWinner, args)

omniORB.registerObjref(PlayerServant._NP_RepositoryId, _objref_PlayerServant)
_0_BoggleApp._objref_PlayerServant = _objref_PlayerServant
del PlayerServant, _objref_PlayerServant

# PlayerServant skeleton
__name__ = "BoggleApp__POA"
class PlayerServant (PortableServer.Servant):
    _NP_RepositoryId = _0_BoggleApp.PlayerServant._NP_RepositoryId


    _omni_op_d = {"logInToGame": _0_BoggleApp.PlayerServant._d_logInToGame, "getLeaderBoard": _0_BoggleApp.PlayerServant._d_getLeaderBoard, "getWaitingTime": _0_BoggleApp.PlayerServant._d_getWaitingTime, "startGame": _0_BoggleApp.PlayerServant._d_startGame, "getRoundTime": _0_BoggleApp.PlayerServant._d_getRoundTime, "startRound": _0_BoggleApp.PlayerServant._d_startRound, "getLetterSet": _0_BoggleApp.PlayerServant._d_getLetterSet, "checkWord": _0_BoggleApp.PlayerServant._d_checkWord, "getRoundWinner": _0_BoggleApp.PlayerServant._d_getRoundWinner, "getGameWinner": _0_BoggleApp.PlayerServant._d_getGameWinner}

PlayerServant._omni_skeleton = PlayerServant
_0_BoggleApp__POA.PlayerServant = PlayerServant
omniORB.registerSkeleton(PlayerServant._NP_RepositoryId, PlayerServant)
del PlayerServant
__name__ = "BoggleApp"

#
# End of module "BoggleApp"
#
__name__ = "boggle_idl"

_exported_modules = ( "BoggleApp", )

# The end.
