# DO NOT EDIT THIS FILE!
#
# Python module BoggleApp generated by omniidl

import omniORB
omniORB.updateModule("BoggleApp")

# ** 1. Stub files contributing to this module
import boggle_idl

# ** 2. Sub-modules

# ** 3. End
