package BoggleApp;


/**
* BoggleApp/LetterListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggle.idl
* Thursday, May 16, 2024 3:05:57 PM SGT
*/

public final class LetterListHolder implements org.omg.CORBA.portable.Streamable
{
  public char value[] = null;

  public LetterListHolder ()
  {
  }

  public LetterListHolder (char[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggleApp.LetterListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggleApp.LetterListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggleApp.LetterListHelper.type ();
  }

}
