package BoggleApp;


/**
* BoggleApp/NoUserFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggle.idl
* Thursday, May 16, 2024 3:05:57 PM SGT
*/

public final class NoUserFoundException extends org.omg.CORBA.UserException
{
  public String message = null;

  public NoUserFoundException ()
  {
    super(NoUserFoundExceptionHelper.id());
  } // ctor

  public NoUserFoundException (String _message)
  {
    super(NoUserFoundExceptionHelper.id());
    message = _message;
  } // ctor


  public NoUserFoundException (String $reason, String _message)
  {
    super(NoUserFoundExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class NoUserFoundException
