package BoggleApp;

/**
* BoggleApp/NoUserFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggle.idl
* Thursday, May 16, 2024 3:05:57 PM SGT
*/

public final class NoUserFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggleApp.NoUserFoundException value = null;

  public NoUserFoundExceptionHolder ()
  {
  }

  public NoUserFoundExceptionHolder (BoggleApp.NoUserFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggleApp.NoUserFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggleApp.NoUserFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggleApp.NoUserFoundExceptionHelper.type ();
  }

}
