package BoggleApp;


/**
* BoggleApp/PlayerListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggle.idl
* Thursday, May 16, 2024 3:05:57 PM SGT
*/

abstract public class PlayerListHelper
{
  private static String  _id = "IDL:BoggleApp/PlayerList:1.0";

  public static void insert (org.omg.CORBA.Any a, BoggleApp.Player[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BoggleApp.Player[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = BoggleApp.PlayerHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (BoggleApp.PlayerListHelper.id (), "PlayerList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BoggleApp.Player[] read (org.omg.CORBA.portable.InputStream istream)
  {
    BoggleApp.Player value[] = null;
    int _len0 = istream.read_long ();
    value = new BoggleApp.Player[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = BoggleApp.PlayerHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BoggleApp.Player[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      BoggleApp.PlayerHelper.write (ostream, value[_i0]);
  }

}
