package BoggleApp;

/**
* BoggleApp/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggle.idl
* Thursday, May 16, 2024 3:05:57 PM SGT
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggleApp.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (BoggleApp.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggleApp.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggleApp.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggleApp.PlayerHelper.type ();
  }

}
