package BoggleApp;


/**
* BoggleApp/PlayerServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggle.idl
* Thursday, May 16, 2024 3:05:57 PM SGT
*/

public interface PlayerServantOperations 
{
  int logInToGame (String username, String password) throws BoggleApp.NoUserFoundException;
  BoggleApp.Player[] getLeaderBoard ();
  int getWaitingTime ();
  int startGame (int playerID);
  int getRoundTime (int gameID);
  int startRound (int gameID, int round);
  char[] getLetterSet (int gameID, int roundID);
  boolean checkWord (String word, int playerID, int roundID) throws BoggleApp.WordNotFoundException;
  String getRoundWinner (int roundID);
  String getGameWinner (int gameID);
} // interface PlayerServantOperations
