package BoggleApp;

/**
* BoggleApp/PlayerServantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggle.idl
* Thursday, May 16, 2024 3:05:57 PM SGT
*/

public final class PlayerServantHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggleApp.PlayerServant value = null;

  public PlayerServantHolder ()
  {
  }

  public PlayerServantHolder (BoggleApp.PlayerServant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggleApp.PlayerServantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggleApp.PlayerServantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggleApp.PlayerServantHelper.type ();
  }

}
